title: Sebastien Larivee
logo: # /assets/img/logo.png
description:
google_analytics:

# Build settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /projects/:name
